Staked farms tab
Plenty-DeFi/plenty-interface pull request #405
Opened 2021-12-13 20:37 UTC by Oli8

![image](https://user-images.githubusercontent.com/13274293/145884640-95d3c329-0f88-4fb4-ae7e-456991866fe1.png)

"Staked Farms" tab on the farms page to quickly get to those you deposited to.

2021-12-14 06:17 UTC, vijaypushkin requested changes

2021-12-14 06:17 UTC, vijaypushkin commented on src/Pages/Farms.js
> +              <Tab eventKey={FARM_TAB.STAKED} title={FARM_TAB.STAKED} />
Can you make the tab scrollable in Mobile?

2021-12-14 06:21 UTC, vijaypushkin requested changes
Hey, Congrats on your first PR! 

Please resolve one review comment

2021-12-14 06:21 UTC, vijaypushkin commented on src/Pages/Farms.js
> +              <Tab eventKey={FARM_TAB.STAKED} title={FARM_TAB.STAKED} />
Can you make tabs scrollable in mobile view?

2021-12-14 12:24 UTC, Oli8 commented on src/Pages/Farms.js
> +              <Tab eventKey={FARM_TAB.STAKED} title={FARM_TAB.STAKED} />
Not sure what you mean, the tabs content or the tabs label list ?

2021-12-14 16:10 UTC, berndoostrum commented on src/Pages/Farms.js
> +              <Tab eventKey={FARM_TAB.STAKED} title={FARM_TAB.STAKED} />
epic stuff @Oli8! We were thinking about adding something like that, but we need to find a way to differentiate 3 other tabs with "staked farms". Maybe we could add a switch instead like pancakeswap? 
![image](https://user-images.githubusercontent.com/12640891/146035597-6b8e9371-3064-4a9f-9caa-797f54bb8e22.png)

2021-12-14 16:30 UTC, Oli8 commented on src/Pages/Farms.js
> +              <Tab eventKey={FARM_TAB.STAKED} title={FARM_TAB.STAKED} />
![image](https://user-images.githubusercontent.com/13274293/146038994-e35cf023-5436-4589-bc3a-1d612ec7f21c.png)

I got this now, you can horizontally scroll to the staked farm tab.
What do you think?

2021-12-14 17:37 UTC, Oli8 commented on src/Pages/Farms.js
> +              <Tab eventKey={FARM_TAB.STAKED} title={FARM_TAB.STAKED} />
> epic stuff @Oli8! We were thinking about adding something like that, but we need to find a way to differentiate 3 other tabs with "staked farms". Maybe we could add a switch instead like pancakeswap? ![image](https://user-images.githubusercontent.com/12640891/146035597-6b8e9371-3064-4a9f-9caa-797f54bb8e22.png)

Thanks ! Yeah maybe a switch would make more sense and would be better ux wise, I'll try something tomorrow.

2021-12-16 10:44 UTC, Oli8 commented on src/Pages/Farms.js
> +              <Tab eventKey={FARM_TAB.STAKED} title={FARM_TAB.STAKED} />
![image](https://user-images.githubusercontent.com/13274293/146357047-69f20759-ab9a-492a-8062-1d235792506f.png)
Implemented the switch

2021-12-20 17:42 UTC, Oli8 commented on src/Pages/Farms.js
> +              <Tab eventKey={FARM_TAB.STAKED} title={FARM_TAB.STAKED} />
Guys ? :)

2021-12-21 14:29 UTC, Oli8 commented
Up

2021-12-22 23:08 UTC, malviyaop commented on src/Pages/Farms.js
> +              <Tab eventKey={FARM_TAB.STAKED} title={FARM_TAB.STAKED} />
@vijaypushkin can you review now?

2021-12-23 01:56 UTC, vijaypushkin requested changes

2021-12-23 01:56 UTC, vijaypushkin commented on src/Pages/Farms.js
> +    if (props.isStakedOnlyOpen) {
Follow the same method as `filterBySearch` and `filterByTab`

2021-12-26 18:55 UTC, Oli8 commented on src/Pages/Farms.js
> +    if (props.isStakedOnlyOpen) {
Done

2021-12-27 02:32 UTC, vijaypushkin approved these changes

2021-12-27 02:32 UTC, merged