Header changes
Plenty-DeFi/plenty-interface pull request #457
Opened 2022-01-04 15:18 UTC by ishwaryaa-b

2022-01-05 11:49 UTC, vijaypushkin requested changes
## TODO

- [ ] Break Header.js into multiple
- [ ] Use data driven design with map on HeaderBottom.js
- [ ] Remove unwanted code

2022-01-05 11:49 UTC, vijaypushkin commented on src/Components/Header/Header.js
> +              <Nav.Item className="ml-auto d-none   align-self-end">
Make it as separate components `<ThemeToggler />`

2022-01-05 11:49 UTC, vijaypushkin commented on src/Components/Header/Header.js
>                <Navbar.Toggle
`<HeaderMenuItem />`

2022-01-05 11:49 UTC, vijaypushkin commented on src/Components/Header/Header.js
>                      <Nav.Link
Make it as separate components `<HeaderMenuSubItem type={'external' | 'internal'} />`

2022-01-05 11:49 UTC, vijaypushkin commented on src/Components/Header/Header.js
>    const connectWalletButton = () => {
`<SignInButton />`

2022-01-05 11:49 UTC, vijaypushkin commented on src/Components/Header/HeaderBottom.js
> +          {props.selectedHeader === HEADER_MODAL.TRADE && (
Too many repeating elements, use this

```ts
const headerItem = [
  {
    name: 'Trade',
    items: [
      {
        name: 'Swap',
        onClick: () => null,
        // href in case of link
       href: 'info.plentydefi.com'
      }
    ]
  }
]
```
and use `map`

2022-01-05 11:49 UTC, vijaypushkin commented on src/Pages/Governance/Governance.js
> +        {/* <Header
Remove code, instead of commenting out. It will be safe in git history

2022-01-05 11:49 UTC, vijaypushkin commented on src/assets/scss/partials/header/_header.scss
> +        //   &:checked ~ .check {
remove

2022-01-06 13:15 UTC, ishwaryaa-b commented
WIP

2022-01-06 13:15 UTC, closed without merging